services:
  postgres:
    image: postgres:16
    container_name: pramara-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pramara_pms
      POSTGRES_USER: pramara
      POSTGRES_PASSWORD: pramara
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest  # stable tag (avoids missing tag errors)
    container_name: pramara-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
